#!/usr/bin/env python3
"""Generate the browser preview from the RUKA2 arm and the current rover URDF."""

from pathlib import Path
import subprocess
import tempfile
import xml.etree.ElementTree as ET
import yaml


ROOT = Path(__file__).resolve().parents[2]
ARM_MACRO = ROOT / "robot/RUKA2/ruka2_description/urdf/ruka2_macro.urdf.xacro"
ROVER_URDF = ROOT / "ui/public/assets/rover/urdf/silverhand_rover.urdf"
OUTPUT = ROOT / "ui/public/assets/system/urdf/rukahod_system.urdf"
LIMITS_OUTPUT = ROOT / "ui/src/kinematics/ruka2Limits.generated.ts"
CHAIN_OUTPUT = ROOT / "ui/src/kinematics/ruka2Chain.generated.ts"
INITIAL_OUTPUT = ROOT / "ui/src/kinematics/ruka2Initial.generated.ts"


def arm_description() -> ET.Element:
    if not ARM_MACRO.is_file():
        raise SystemExit("RUKA2 submodule is missing; run: git submodule update --init robot/RUKA2")
    wrapper = f'''<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ruka2">
      <xacro:include filename="{ARM_MACRO}"/>
      <xacro:ruka2_model use_end_effector="false" end_effector_type="none"
        enable_gripper_motion="false"/>
    </robot>'''
    with tempfile.NamedTemporaryFile(mode="w", suffix=".urdf.xacro") as source:
        source.write(wrapper)
        source.flush()
        try:
            result = subprocess.run(
                ["bash", "-c", 'source /opt/ros/jazzy/setup.bash && xacro "$1"', "bash", source.name],
                text=True,
                capture_output=True,
                check=True,
            )
        except subprocess.CalledProcessError as exc:
            raise SystemExit(f"RUKA2 xacro failed:\n{exc.stderr}") from exc
    return ET.fromstring(result.stdout)


def main() -> None:
    rover = ET.parse(ROVER_URDF).getroot()
    arm = arm_description()
    limits = []
    chain = []
    for index in range(1, 7):
        joint = arm.find(f"joint[@name='joint_{index}']")
        if joint is None or joint.find("limit") is None:
            raise RuntimeError(f"RUKA2 joint_{index} has no limits")
        limit = joint.find("limit")
        limits.append(f"  joint_{index}: {{ min: {limit.get('lower')}, max: {limit.get('upper')} }},")
        origin = joint.find("origin")
        axis = joint.find("axis")
        if origin is None or axis is None:
            raise RuntimeError(f"RUKA2 joint_{index} has no origin or axis")
        xyz = ", ".join(origin.get("xyz").split())
        rpy = ", ".join(origin.get("rpy").split())
        direction = ", ".join(axis.get("xyz").split())
        chain.append(f"  {{ xyz: [{xyz}], rpy: [{rpy}], axis: [{direction}] }},")
    LIMITS_OUTPUT.write_text(
        "// Generated by ui/scripts/build-system-urdf.py from robot/RUKA2.\n"
        "export const RUKA2_JOINT_LIMITS_RAD = {\n"
        + "\n".join(limits) + "\n} as const;\n",
        encoding="utf-8",
    )
    tool_joint = arm.find("joint[@name='link_06__tool0']")
    if tool_joint is None or tool_joint.find("origin") is None:
        raise RuntimeError("RUKA2 tool0 joint is missing")
    tool_origin = tool_joint.find("origin")
    tool_xyz = ", ".join(tool_origin.get("xyz").split())
    tool_rpy = ", ".join(tool_origin.get("rpy").split())
    CHAIN_OUTPUT.write_text(
        "// Generated by ui/scripts/build-system-urdf.py from robot/RUKA2.\n"
        "export const RUKA2_CHAIN = [\n" + "\n".join(chain) + "\n] as const;\n"
        f"export const RUKA2_TOOL = {{ xyz: [{tool_xyz}], rpy: [{tool_rpy}] }} as const;\n",
        encoding="utf-8",
    )
    initial_file = ROOT / "robot/RUKA2/ruka2_control/config/initial_positions.yaml"
    initial = yaml.safe_load(initial_file.read_text(encoding="utf-8"))["initial_positions"]
    initial_values = ", ".join(f"{float(initial[f'joint_{index}'])} * 180 / Math.PI" for index in range(1, 7))
    INITIAL_OUTPUT.write_text(
        "// Generated by ui/scripts/build-system-urdf.py from robot/RUKA2.\n"
        f"export const RUKA2_INITIAL_JOINTS_DEG = [{initial_values}] as const;\n",
        encoding="utf-8",
    )
    rover.attrib["name"] = "rukahod_system"

    rover_links = {link.attrib["name"] for link in rover.findall("link")}
    arm_links = {link.attrib["name"] for link in arm.findall("link")}
    if rover_links & arm_links != {"base_link"}:
        raise RuntimeError(f"Unexpected link name overlap: {rover_links & arm_links}")

    for element in arm:
        if element.tag == "link" and element.get("name") == "base_link":
            element.set("name", "arm_base_link")
        for relation in element.findall(".//parent") + element.findall(".//child"):
            if relation.get("link") == "base_link":
                relation.set("link", "arm_base_link")
        materials = element.findall(".//material")
        if element.tag == "material":
            materials.append(element)
        for material in materials:
            if material.get("name"):
                material.set("name", "ruka2_" + material.get("name"))
        rover.append(element)

    mount = ET.SubElement(rover, "joint", name="rover_to_arm", type="fixed")
    ET.SubElement(mount, "parent", link="base_link")
    ET.SubElement(mount, "child", link="arm_base_link")
    ET.SubElement(mount, "origin", xyz="0.324 0 -0.076", rpy="0 0 0")

    ET.indent(rover, space="  ")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        '<!-- Generated by ui/scripts/build-system-urdf.py from robot/RUKA2. -->\n'
        + ET.tostring(rover, encoding="unicode") + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
